name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          tools: composer
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Create .env
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Prepare database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --force
      - name: Run tests
        run: php artisan test --testsuite=Unit,Feature --stop-on-failure
